version: '3'
services:
  frontend:
    build:
      context: ./app/frontend
      target: dev
    ports:
      - '8080:5173'
    volumes:
      - './app/frontend:/app'
      - "/app/node_modules"
    depends_on:
      - backend
  backend:
    build:
      context: ./app/backend
      target: dev
    ports:
      - '3000:3000'
    volumes:
      - './app/backend:/app'
      - "/app/node_modules"
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    restart: always
    shm_size: 128mb
    ports:
      - '5432:5432'
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: password
volumes:
  dbdata:
