version: '3'
services:
  backend:
    build:
      context: ./app/backend
      target: prod
    restart: always
    ports:
      - 80:3000
    depends_on:
      - db
    pull_policy: build
  db:
    image: postgres:16-alpine
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data 
volumes:
  dbdata:
