version: '3'
services:
  frontend:
    build: ./app/frontend
    ports:
      - '8080:80'
    depends_on:
      - backend
  backend:
    build: ./app/backend
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    restart: always
    shm_size: 128mb
    ports:
      - '5432:5432'
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: password
volumes:
  dbdata:
